#!/usr/bin/env bash

# Stop/start Tunnelblick to fix OSX bug

# Change IFACE to match your WiFi interface 
# (en0 on Macbook Air and Retina, en1 on old Macbook Pros with ethernet) 
IFACE=en0
networksetup -setairportpower $IFACE off
sudo ifconfig $IFACE down
sleep 1
sudo route flush
sudo ifconfig $IFACE up
networksetup -setairportpower $IFACE on
