#!/usr/bin/env bash

# Stop/start Tunnelblick to fix OSX bug
IFACE=${1:-en0}

networksetup -setairportpower $IFACE off
sudo ifconfig $IFACE down
sleep 1
sudo route flush
sudo ifconfig $IFACE up
networksetup -setairportpower $IFACE on
